<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityPassagemProxy extends \Fapesc\TutorialBundle\Entity\Passagem implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function getTipos()
    {
        $this->__load();
        return parent::getTipos();
    }

    public function getTipoSelect()
    {
        $this->__load();
        return parent::getTipoSelect();
    }

    public function setOrigem($origem)
    {
        $this->__load();
        return parent::setOrigem($origem);
    }

    public function getOrigem()
    {
        $this->__load();
        return parent::getOrigem();
    }

    public function setSaida($saida)
    {
        $this->__load();
        return parent::setSaida($saida);
    }

    public function getSaida($format = 'd/m/Y H:i')
    {
        $this->__load();
        return parent::getSaida($format);
    }

    public function setDestino($destino)
    {
        $this->__load();
        return parent::setDestino($destino);
    }

    public function getDestino()
    {
        $this->__load();
        return parent::getDestino();
    }

    public function setChegada($chegada)
    {
        $this->__load();
        return parent::setChegada($chegada);
    }

    public function getChegada($format = 'd/m/Y H:i')
    {
        $this->__load();
        return parent::getChegada($format);
    }

    public function setTiquete($tiquete)
    {
        $this->__load();
        return parent::setTiquete($tiquete);
    }

    public function getTiquete()
    {
        $this->__load();
        return parent::getTiquete();
    }

    public function setCompra($compra)
    {
        $this->__load();
        return parent::setCompra($compra);
    }

    public function getCompra($format = 'd/m/Y')
    {
        $this->__load();
        return parent::getCompra($format);
    }

    public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }

    public function getValor($puro = false)
    {
        $this->__load();
        return parent::getValor($puro);
    }

    public function setObjetivo($objetivo)
    {
        $this->__load();
        return parent::setObjetivo($objetivo);
    }

    public function getObjetivo()
    {
        $this->__load();
        return parent::getObjetivo();
    }

    public function setResultado($resultado)
    {
        $this->__load();
        return parent::setResultado($resultado);
    }

    public function getResultado()
    {
        $this->__load();
        return parent::getResultado();
    }

    public function setFornecedor(\Fapesc\TutorialBundle\Entity\Fornecedor $fornecedor)
    {
        $this->__load();
        return parent::setFornecedor($fornecedor);
    }

    public function getFornecedor()
    {
        $this->__load();
        return parent::getFornecedor();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate($data)
    {
        $this->__load();
        return parent::populate($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tipo', 'fornecedor', 'origem', 'saida', 'destino', 'chegada', 'tiquete', 'compra', 'valor', 'objetivo', 'resultado');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}