<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntitySalarioProxy extends \Fapesc\TutorialBundle\Entity\Salario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setCarga($carga)
    {
        $this->__load();
        return parent::setCarga($carga);
    }

    public function getCarga()
    {
        $this->__load();
        return parent::getCarga();
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function getData($format = 'm/Y')
    {
        $this->__load();
        return parent::getData($format);
    }

    public function setBruto($bruto)
    {
        $this->__load();
        return parent::setBruto($bruto);
    }

    public function getBruto($puro = false)
    {
        $this->__load();
        return parent::getBruto($puro);
    }

    public function setProporcional($proporcional)
    {
        $this->__load();
        return parent::setProporcional($proporcional);
    }

    public function getProporcional($puro = false)
    {
        $this->__load();
        return parent::getProporcional($puro);
    }

    public function setPesquisador(\Fapesc\TutorialBundle\Entity\Pesquisador $pesquisador)
    {
        $this->__load();
        return parent::setPesquisador($pesquisador);
    }

    public function getPesquisador()
    {
        $this->__load();
        return parent::getPesquisador();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate($data)
    {
        $this->__load();
        return parent::populate($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'carga', 'data', 'bruto', 'proporcional', 'pesquisador');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}