<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityResultadoProxy extends \Fapesc\TutorialBundle\Entity\Resultado implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setResultado($resultado)
    {
        $this->__load();
        return parent::setResultado($resultado);
    }

    public function getResultado($extenso = false)
    {
        $this->__load();
        return parent::getResultado($extenso);
    }

    public function setJustificativa($justificativa)
    {
        $this->__load();
        return parent::setJustificativa($justificativa);
    }

    public function getJustificativa()
    {
        $this->__load();
        return parent::getJustificativa();
    }

    public function setMeta($meta)
    {
        $this->__load();
        return parent::setMeta($meta);
    }

    public function getMeta()
    {
        $this->__load();
        return parent::getMeta();
    }

    public function setRelatorio(\Fapesc\TutorialBundle\Entity\Relatorio $relatorio)
    {
        $this->__load();
        return parent::setRelatorio($relatorio);
    }

    public function getRelatorio()
    {
        $this->__load();
        return parent::getRelatorio();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'resultado', 'justificativa', 'meta', 'relatorio');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}