<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityBolsistaProxy extends \Fapesc\TutorialBundle\Entity\Bolsista implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setCpf($cpf)
    {
        $this->__load();
        return parent::setCpf($cpf);
    }

    public function getCpf()
    {
        $this->__load();
        return parent::getCpf();
    }

    public function setInstituicao($instituicao)
    {
        $this->__load();
        return parent::setInstituicao($instituicao);
    }

    public function getInstituicao()
    {
        $this->__load();
        return parent::getInstituicao();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo($puro = true)
    {
        $this->__load();
        return parent::getTipo($puro);
    }

    public function getTipos()
    {
        $this->__load();
        return parent::getTipos();
    }

    public function getTipoSelect()
    {
        $this->__load();
        return parent::getTipoSelect();
    }

    public function setMatricula($matricula)
    {
        $this->__load();
        return parent::setMatricula($matricula);
    }

    public function getMatricula()
    {
        $this->__load();
        return parent::getMatricula();
    }

    public function setEndereco($endereco)
    {
        $this->__load();
        return parent::setEndereco($endereco);
    }

    public function getEndereco()
    {
        $this->__load();
        return parent::getEndereco();
    }

    public function setCidade($cidade)
    {
        $this->__load();
        return parent::setCidade($cidade);
    }

    public function getCidade()
    {
        $this->__load();
        return parent::getCidade();
    }

    public function setUf($uf)
    {
        $this->__load();
        return parent::setUf($uf);
    }

    public function getUf()
    {
        $this->__load();
        return parent::getUf();
    }

    public function setCep($cep)
    {
        $this->__load();
        return parent::setCep($cep);
    }

    public function getCep()
    {
        $this->__load();
        return parent::getCep();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTelefone($telefone)
    {
        $this->__load();
        return parent::setTelefone($telefone);
    }

    public function getTelefone()
    {
        $this->__load();
        return parent::getTelefone();
    }

    public function setCelular($celular)
    {
        $this->__load();
        return parent::setCelular($celular);
    }

    public function getCelular()
    {
        $this->__load();
        return parent::getCelular();
    }

    public function setBanco($banco)
    {
        $this->__load();
        return parent::setBanco($banco);
    }

    public function getBanco()
    {
        $this->__load();
        return parent::getBanco();
    }

    public function setConta($conta)
    {
        $this->__load();
        return parent::setConta($conta);
    }

    public function getConta()
    {
        $this->__load();
        return parent::getConta();
    }

    public function setAgencia($agencia)
    {
        $this->__load();
        return parent::setAgencia($agencia);
    }

    public function getAgencia()
    {
        $this->__load();
        return parent::getAgencia();
    }

    public function addBolsa(\Fapesc\TutorialBundle\Entity\Bolsa $bolsas)
    {
        $this->__load();
        return parent::addBolsa($bolsas);
    }

    public function getBolsas()
    {
        $this->__load();
        return parent::getBolsas();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate($data)
    {
        $this->__load();
        return parent::populate($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nome', 'cpf', 'instituicao', 'tipo', 'matricula', 'endereco', 'cidade', 'uf', 'cep', 'email', 'telefone', 'celular', 'banco', 'conta', 'agencia', 'bolsas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}