<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityDiariaProxy extends \Fapesc\TutorialBundle\Entity\Diaria implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setInicio($inicio)
    {
        $this->__load();
        return parent::setInicio($inicio);
    }

    public function getInicio($format = 'd/m/Y')
    {
        $this->__load();
        return parent::getInicio($format);
    }

    public function setFim($fim)
    {
        $this->__load();
        return parent::setFim($fim);
    }

    public function getFim($format = 'd/m/Y')
    {
        $this->__load();
        return parent::getFim($format);
    }

    public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }

    public function getValor($puro = false)
    {
        $this->__load();
        return parent::getValor($puro);
    }

    public function setBeneficiario($beneficiario)
    {
        $this->__load();
        return parent::setBeneficiario($beneficiario);
    }

    public function getBeneficiario()
    {
        $this->__load();
        return parent::getBeneficiario();
    }

    public function setCpf($cpf)
    {
        $this->__load();
        return parent::setCpf($cpf);
    }

    public function getCpf()
    {
        $this->__load();
        return parent::getCpf();
    }

    public function setInstituicao($instituicao)
    {
        $this->__load();
        return parent::setInstituicao($instituicao);
    }

    public function getInstituicao()
    {
        $this->__load();
        return parent::getInstituicao();
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function setObjetivos($objetivos)
    {
        $this->__load();
        return parent::setObjetivos($objetivos);
    }

    public function getObjetivos()
    {
        $this->__load();
        return parent::getObjetivos();
    }

    public function setDestino($destino)
    {
        $this->__load();
        return parent::setDestino($destino);
    }

    public function getDestino()
    {
        $this->__load();
        return parent::getDestino();
    }

    public function setRoteiro($roteiro)
    {
        $this->__load();
        return parent::setRoteiro($roteiro);
    }

    public function getRoteiro()
    {
        $this->__load();
        return parent::getRoteiro();
    }

    public function setResultados($resultados)
    {
        $this->__load();
        return parent::setResultados($resultados);
    }

    public function getResultados()
    {
        $this->__load();
        return parent::getResultados();
    }

    public function setQuantidade($quantidade)
    {
        $this->__load();
        return parent::setQuantidade($quantidade);
    }

    public function getQuantidade()
    {
        $this->__load();
        return parent::getQuantidade();
    }

    public function setDocumentos($documentos)
    {
        $this->__load();
        return parent::setDocumentos($documentos);
    }

    public function getDocumentos()
    {
        $this->__load();
        return parent::getDocumentos();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate($data)
    {
        $this->__load();
        return parent::populate($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'beneficiario', 'cpf', 'instituicao', 'tipo', 'objetivos', 'destino', 'roteiro', 'resultados', 'inicio', 'fim', 'quantidade', 'valor', 'documentos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}