<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityRelatorioProxy extends \Fapesc\TutorialBundle\Entity\Relatorio implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getRubrica($extenso = false)
    {
        $this->__load();
        return parent::getRubrica($extenso);
    }

    public function getRubricas()
    {
        $this->__load();
        return parent::getRubricas();
    }

    public function getRubricaSelect()
    {
        $this->__load();
        return parent::getRubricaSelect();
    }

    public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }

    public function getValor($puro = false)
    {
        $this->__load();
        return parent::getValor($puro);
    }

    public function getTipo($extenso = false)
    {
        $this->__load();
        return parent::getTipo($extenso);
    }

    public function getTipos()
    {
        $this->__load();
        return parent::getTipos();
    }

    public function getTipoSelect()
    {
        $this->__load();
        return parent::getTipoSelect();
    }

    public function setNota($nota)
    {
        $this->__load();
        return parent::setNota($nota);
    }

    public function getNota()
    {
        $this->__load();
        return parent::getNota();
    }

    public function setLiberacao($liberacao)
    {
        $this->__load();
        return parent::setLiberacao($liberacao);
    }

    public function getLiberacao($format = 'd/m/Y')
    {
        $this->__load();
        return parent::getLiberacao($format);
    }

    public function setVigencia($vigencia)
    {
        $this->__load();
        return parent::setVigencia($vigencia);
    }

    public function getVigencia($format = 'd/m/Y')
    {
        $this->__load();
        return parent::getVigencia($format);
    }

    public function setRubrica($rubrica)
    {
        $this->__load();
        return parent::setRubrica($rubrica);
    }

    public function setTipo($tipo)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function setResultado($resultado)
    {
        $this->__load();
        return parent::setResultado($resultado);
    }

    public function getResultado()
    {
        $this->__load();
        return parent::getResultado();
    }

    public function setJustificativa($justificativa)
    {
        $this->__load();
        return parent::setJustificativa($justificativa);
    }

    public function getJustificativa()
    {
        $this->__load();
        return parent::getJustificativa();
    }

    public function setDificuldade($dificuldade)
    {
        $this->__load();
        return parent::setDificuldade($dificuldade);
    }

    public function getDificuldade()
    {
        $this->__load();
        return parent::getDificuldade();
    }

    public function setAlteracao($alteracao)
    {
        $this->__load();
        return parent::setAlteracao($alteracao);
    }

    public function getAlteracao()
    {
        $this->__load();
        return parent::getAlteracao();
    }

    public function setAtivo($ativo)
    {
        $this->__load();
        return parent::setAtivo($ativo);
    }

    public function getAtivo()
    {
        $this->__load();
        return parent::getAtivo();
    }

    public function setProjeto(\Fapesc\TutorialBundle\Entity\Projeto $projeto)
    {
        $this->__load();
        return parent::setProjeto($projeto);
    }

    public function getProjeto()
    {
        $this->__load();
        return parent::getProjeto();
    }

    public function addResultado(\Fapesc\TutorialBundle\Entity\Resultado $resultados)
    {
        $this->__load();
        return parent::addResultado($resultados);
    }

    public function getResultados()
    {
        $this->__load();
        return parent::getResultados();
    }

    public function setConciliacao(\Fapesc\TutorialBundle\Entity\Conciliacao $conciliacao)
    {
        $this->__load();
        return parent::setConciliacao($conciliacao);
    }

    public function getConciliacao()
    {
        $this->__load();
        return parent::getConciliacao();
    }

    public function addEmpenho(\Fapesc\TutorialBundle\Entity\Empenho $empenhos)
    {
        $this->__load();
        return parent::addEmpenho($empenhos);
    }

    public function getEmpenhos()
    {
        $this->__load();
        return parent::getEmpenhos();
    }

    public function addContrapartida(\Fapesc\TutorialBundle\Entity\Contrapartida $contrapartidas)
    {
        $this->__load();
        return parent::addContrapartida($contrapartidas);
    }

    public function getContrapartidas()
    {
        $this->__load();
        return parent::getContrapartidas();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populateDados($dados)
    {
        $this->__load();
        return parent::populateDados($dados);
    }

    public function populateRelatorio($dados)
    {
        $this->__load();
        return parent::populateRelatorio($dados);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nota', 'liberacao', 'vigencia', 'rubrica', 'valor', 'tipo', 'resultado', 'justificativa', 'dificuldade', 'alteracao', 'ativo', 'projeto', 'resultados', 'empenhos', 'contrapartidas', 'conciliacao');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}