<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FapescTutorialBundleEntityBolsaProxy extends \Fapesc\TutorialBundle\Entity\Bolsa implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setDescricao($descricao)
    {
        $this->__load();
        return parent::setDescricao($descricao);
    }

    public function getDescricao()
    {
        $this->__load();
        return parent::getDescricao();
    }

    public function setInicio($inicio)
    {
        $this->__load();
        return parent::setInicio($inicio);
    }

    public function getInicio($puro = true)
    {
        $this->__load();
        return parent::getInicio($puro);
    }

    public function setFim($fim)
    {
        $this->__load();
        return parent::setFim($fim);
    }

    public function getFim($puro = true)
    {
        $this->__load();
        return parent::getFim($puro);
    }

    public function setData($data)
    {
        $this->__load();
        return parent::setData($data);
    }

    public function getData($puro = true)
    {
        $this->__load();
        return parent::getData($puro);
    }

    public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }

    public function getValor($puro = false)
    {
        $this->__load();
        return parent::getValor($puro);
    }

    public function setBolsista(\Fapesc\TutorialBundle\Entity\Bolsista $bolsista)
    {
        $this->__load();
        return parent::setBolsista($bolsista);
    }

    public function getBolsista()
    {
        $this->__load();
        return parent::getBolsista();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function populate($data)
    {
        $this->__load();
        return parent::populate($data);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'descricao', 'inicio', 'fim', 'data', 'valor', 'bolsista');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}